### ISSUE TITLE
Trim before convert

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#103]
I just tried importing a long (2h) video file, in which I wanted to trim out only 1 minute in the middle. It looks like MgObject converts the entire thing to AVI before doing the trimming. That takes a lot of time! 

I think it would be better to trim first, and then convert. Would that cause problems for other objects?

**Comment by balintlaczko** [comment]
Yes, that is a great catch! I think I am doing it in the wrong way, I am actually reencoding the entire thing, using this:
`ffmpeg -i <filename> -c:v mjpeg -q:v 3 <of + '.avi'>`
Instead I will try to just swap the container, like this:
`ffmpeg -i <filename> -codec copy <of + '.avi'>`
I used this in a recent project to convert mkv files to mov or mp4, it seemed to be reliable. I remember there was something with cv2 only liking mjpeg encoding so I might have to fall back to the first method, but will try and see.

**Comment by balintlaczko** [comment]
Okay, so some tests show that cv2 doesn't seem to have a problem with this, and videos are "converted" instantly regardless of their length. All subsequent processes seem to look right. There is one tiny issue though, maybe just on Windows, that the converted videos (before any preprocessing, just after swapping containers) don't play back properly on the built-in media players, they do without problems on VLC. I googled the error code the media player returns, and found the - rather ironic - answers to try using VLC (and some redundant answers about updating graphics drivers). Since the benefit of swapping containers is huge when it comes to very long videos, and the user *has* the original input video already, I assume we can ignore this?... Or not, @alexarje?
While testing, found a more serious bug, see #104 .
If we go with this solution, #102 is also solved, since we copy whatever the audio codec was in the input.

**Comment by balintlaczko** [comment]
So a little update on this. I made the `cast_into_avi()` in `_utils.py` and it works with some videos, and I hit the cv2 codec problem with other types. So without wasting too much time to research this, I decided to revert to using `convert_to_avi()`, which can be painfully slow, but it works 100% with cv2 and with the less capable default windows video player app ("Movies & TV").
In this case I will of course swap the process order, first we trim, then we convert. :)
