### ISSUE TITLE
Add coloured waveforms

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#159]
It would be cool to implement the coloured waveform (freesound-style):

![image](https://user-images.githubusercontent.com/114316/101288703-3f660600-37f8-11eb-860b-13450b2278e8.png)

The code is available in the [Freesound](https://github.com/MTG/freesound/tree/master/utils/audioprocessing) repository (in the wav2png.py script, I guess).

**Comment by joachimpoutaraud** [comment]
I have been working quite extensively recenlty on finding a way to implement the coloured waveform (freesound-style). I found an interesting repository [freesound-thumbnailer](https://github.com/endolith/freesound-thumbnailer/blob/master/processing.py) which needed quite a few modifications in order to work properly.

I finally managed to get nice results and implemented the new functions in two classes available in the [`_colored.py`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_colored.py) script, with the possibility to color a waveform using the standard function `waveform` of the `MgAudio` class. As a result, it is now possible to render coloured waveforms by simply doing the following:

```python
import musicalgestures
source_audio = musicalgestures.MgAudio('path/to/your/audio/file')
source_audio.waveform(colored=True)
```

The function is only available locally at the moment but will be in the next version of the toolbox soon. More information on the coloured waveform functionalities can be found on the [wiki documentation](https://github.com/fourMs/MGT-python/wiki/5-%E2%80%90-Audio%E2%80%90based-Processes#colored).
