### ISSUE TITLE
Use default fonts

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#178]
Looks like the current plots specify a times-like font for titles and labels. I guess it may be better to just use the default fonts and sizes?

**Comment by balintlaczko** [comment]
Ah, good catch! I found the culprit: line 437 in *_motionvideo.py*:
`plt.rc('font', family='serif')`
Not sure what the exact result is. On my system the [default matplotlib font](https://stackoverflow.com/questions/27817912/find-out-which-font-matplotlib-uses) is Dejavu Sans. I never tried to change that, but I also never checked if some older code did. I guess once this is set to `plt` all the subsequent figures will use this instead of the default one? Anyway, will remove this and see if there is any change.

**Comment by balintlaczko** [comment]
Seems to be solved now.
Before:
![image](https://user-images.githubusercontent.com/45127463/103314517-a6579300-4a23-11eb-8fbc-9058b2599454.png)

After:
![image](https://user-images.githubusercontent.com/45127463/103314534-b3748200-4a23-11eb-8775-b993ab916213.png)
