### ISSUE TITLE
.videograms() does not show progress bar correctly

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#193]
When running .videograms() it only outputs the progress bar (with 100%) once the process is done.

**Comment by balintlaczko** [comment]
Yes, this is perfectly normal. The underlying reason is that when one executes an FFmpeg command with the flag `-frames 1`, there is not really any progress coming from the stdout, except for that one frame it is processing. Actually I even had to implement the `stream` boolean parameter for `_utils.ffmpeg_cmd()` to be able to switch off polling on `videograms()`, because caused a runaway memory leak (#179).
