### ISSUE TITLE
Skip frames based on keyframes

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#196]
To improve processing speed and utilize the inner potential of MP4 files, I think it would be good to include a mode "keyframes" for the skip frame function. This could be based on extracting only the keyframes of the video file, such as this: 

`ffmpeg -skip_frame nokey -i $filename`

**Comment by joachimpoutaraud** [comment]
After some research on the ffmpeg documentation, I found that it was also possible to `-discard` the keyframes of the video in order to keep only the keyframes (i.e. `-discard nokey`). 

The `-skip_frame` is useful to skip the decoding of the frames but when processing the video file I found that discarding the frames was reducing even more the size of the video file. I will therefore implemented this as a new parameter for the video preprocessing.

**Comment by joachimpoutaraud** [comment]
I have updated the [`fixing`](https://github.com/fourMs/MGT-python/wiki/3-%E2%80%90-Preprocessing#fixing) function and added the possibility to extract only the keyframes of the video file in order to improve processing speed and utilize the inner potential of MP4 files. This can be achieve by setting the parameter `frames=-1`. More information [here](https://github.com/fourMs/MGT-python/wiki/3-%E2%80%90-Preprocessing#fixing).

This is only available on the local repository at the moment but I will update a new version of the repository on PyPI with some other functions shortly.
