### ISSUE TITLE
Naming of average images

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#202]
I am setting up a script for batch processing a number of files. I want to create: 

- videograms
- average image (of regular video)
- motiongrams
- motion average image

Problem 1: If I do: 

```
videofile = mg.MgObject(video)
videofile.average()
videofile.videograms()
videofile.motion()
videofile.average()
```
I see that the second `average()` writes a file over the first one. So we need a way of naming these to avoid that to happen. 

Problem 2: I see that for the above sequence the conversion from .MP4 file to .AVI happens twice. Not sure how to avoid that?

Problem 3: How can I chain this in the best way? Running `videofile.motion().average()` seems to work as expected, but not sure about the other operations? Not really sure if there is any computational benefit to chaining either, or if it is only a naming convenience?

**Comment by balintlaczko** [comment]
> So we need a way of naming these to avoid that to happen.

Absolutely! This is generally a good point for several functions in the package. Will make an issue for it.

> the conversion from .MP4 file to .AVI happens twice. Not sure how to avoid that?

That's a trickier one, since there is no way for us to know whether 'dance.avi' and a 'dance.mp4' in the same folder correspond to the same or different content. Ideally we should not need to convert at all. Implementing the `motion` with ffmpeg is still a plan, though I had to stop trying after I ran into some weird issues with it. I don't remember if there was a similar issue with the average image or I just haven't tried, but will look into that. For now I recommend just converting your video to avi beforehand if you use funcions that rely on opencv (that is: `average`, `motion`, `flow.dense`, `flow.sparse`, `pose`). The way to do it is:
```
myvideo = '/path/to/myvideo.mp4'
video_as_avi = musicalgestures._utils.convert_to_avi(myvideo)
mg = musicalgestures.MgObject(video_as_avi)
```

> How can I chain this in the best way?

I am not sure you need to chain in this case. Chaining is also just a convenience shortcut, I don't think it has too much computational benefit (it probably has a very slight one). Chaining is mostly for the scenario when you want to do several things always using the last output as input. Like:
```
musicalgestures.MgObject('myvideo.avi').motion().history().average()
```
If you want to do several things with the _same_ file, then you don't need chaining.
