### ISSUE TITLE
Keyframe history images

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#203]
I have been exploring what can be called *keyframe history images* in some blog posts ([here](https://www.arj.no/2021/02/04/bach-prelude/) and [here](https://www.arj.no/2020/02/21/aist-visualizations/). The idea here is to extract only the keyframes from the video and superimpose them on top of each other. I have made some working code in [MGT-Terminal](https://github.com/fourMs/MGT-terminal). There it is based on two functions: 

1. extract keyframes with [mgkeyframes.sh](https://github.com/fourMs/MGT-terminal/blob/master/code/mgkeyframes.sh)
2. combine keyframes with either [mgbackground.sh](https://github.com/fourMs/MGT-terminal/blob/master/code/mgbackground.sh) or [mgforeground.sh](https://github.com/fourMs/MGT-terminal/blob/master/code/mgforeground.sh)

It would be nice to get make this into a function for MGT-python as well.

**Comment by joachimpoutaraud** [comment]
I have been working on extracting keyframes using `ffmpeg` and used `opencv-python` to combine the video keyframes all together with the possibility to render either the motion history image of the foreground or the background.

I worked using a [contemporary dance video](https://www.youtube.com/watch?v=Vj-g4MsRKds&feature=emb_title) but I still struggle to superimpose the body silhouette with the same intensity for the final motion history image. The problem is that when I overlay the keyframes on top of each other it decreases the intensity of the previous frame.

Here is an overview of the result I obtained so far with a transparency of `alpha=0.2`:
![test](https://user-images.githubusercontent.com/63192177/182201508-c77cce54-7a96-49d8-b4bb-15fadaceaad9.jpeg)

and with a transparency of `alpha=0.5`:
![testy](https://user-images.githubusercontent.com/63192177/182203005-f64663cf-e7f8-4a79-939f-49557d18f0c7.jpeg)

I have also tried to extract the contours of the moving object in the video, in order to convert the background to transparent and overlay the motion frames without background but the result is still not convincing as the contour isn't really accurate.

**Comment by alexarje** [comment]
Yes, it is tricky to make these look nice (and generalizable). We can leave this issue open and revisit it when we have better ideas for implementing it.

**Comment by joachimpoutaraud** [comment]
I have been investigated a bit more this issue and find a good alternative using the new function of the toolbox [`blend`](https://github.com/fourMs/MGT-python/wiki/4-%E2%80%90-Video%E2%80%90based-Processes#blend).

So, to extract a keyframe history image of a video file you can now do the following:

```python
import musicalgestures
# Extract keyframes of the video by specifying the parameter `frames=-1`
source_video = musicalgestures.MgVideo('input_files/video/test.mp4', frames=-1)
# Run the blend function using the component mode `darken` or `lighten` depending on the color of your background
keyframe_history = source_video.blend(component_mode='darken')
keyframe_history.show(mode='notebook')
```

As a result, I get a nice keyframe history image for the [contemporary dance video](https://www.youtube.com/watch?v=Vj-g4MsRKds&feature=emb_title).

![image](https://github.com/fourMs/MGT-python/assets/63192177/bebf859b-e4e9-46b5-b798-bf350d47891d)

The only tricky part is to set the appropriate `component_mode` for rendering the keyframe history image. For instance, using the `darken` component mode is more adapted for light background, whereas the `lighten` component mode is more adapted for dark background. 

Here is another example on the [contemporary dance video](https://www.youtube.com/watch?v=Vj-g4MsRKds&feature=emb_title) using the `lighten` component mode. As we can see, it works less well because we only see the white outline of the dancer.

![image](https://github.com/fourMs/MGT-python/assets/63192177/44e31929-094f-478f-812d-1f21ccde9e71)
