### ISSUE TITLE
Hang on manual crop on Ubuntu 20.10

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#206]
Testing manual cropping on Ubuntu with the latest RC 0.99. After clicking c in the pop-up window, the process just hangs. When I interrupt, I get the following message: 

![Screenshot from 2021-03-05 08-33-10](https://user-images.githubusercontent.com/114316/110082311-744d0f00-7d8d-11eb-8b31-1b17b9af15b1.png)

**Comment by balintlaczko** [comment]
Could not reproduce this on Ubuntu 20.04.2 LTS and Windows 10.0.19041. Does the issue happen consistently on your side?

The `x.join()` line there where it halts is the main thread waiting for the other (where the cropping happens) to finish its job. I know it looks funny to create another thread just for the cropping (which we generally want to be a synchronous thing), but this was the only way I could come up with to avoid the `cv2.waitKey()` segfault crash (issue #200). (by creating an async subprocess launched in a sub-thread, only to get collected in the main thread and process again when it's done - it was a fierce battle, but seems to be stable on my end(s)...)

**Comment by balintlaczko** [comment]
I have tested this multiple times on my Ubuntu VM, and it seems to work well. Feel free to reopen this issue if you find anything funky! :)

**Comment by alexarje** [comment]
I still have the same problem with hanging. I get the window, make a selection and press "c". Then is just hangs. Here is the output after an interrupt:

![Screenshot from 2021-05-23 22-08-07](https://user-images.githubusercontent.com/114316/119275133-9d09d580-bc13-11eb-864d-be1a98f37b9f.png)

**Comment by balintlaczko** [comment]
Hey @alexarje, sorry to see that this is still an issue. Can I ask what is your OS? I use Ubuntu 20.04.2 LTS (64bit, X11, Gnome 3.36.8), and it works fine, so my guess is that it is somehow related to the OS difference between our systems. The part that seems to hang is the built-in `threading.Thread.join()` function. My guess is that some eventloop-related fuctions have changed their behaviour on your OS and it creates a deadlock. I can't reproduce it on my Ubuntu, but I'll write a set of test codes and pm you with them. :)

**Comment by balintlaczko** [comment]
Turns out this seems to be an issue with Ubuntu 20.10, @alexarje confirms that it works on 20.04. Have to keep looking what difference causes the deadlock.

**Comment by balintlaczko** [comment]
I think that all this time this has been a problem with Tkinter on Linux. The reason was probably an [unsuccessful installation of some packages](https://github.com/fourMs/MGT-python/wiki/0-%E2%80%90-Installation#linux). If you haven't manually install Tkinter (with `sudo apt-get install python3-tk`) then the [function call](https://github.com/fourMs/MGT-python/blob/cf8c19bec3159c1c1b8b120cffdd6e11d58dd418/musicalgestures/_utils.py#L1161) that *used to* initialize Tkinter can cause a hang. All the hackery with Tkinter was actually just to get the scaled screen resolution which is not worth this compatibility risk (not to mention that I have not handled the case of *not having* a display), so I removed this call from the cropping window code, and now use a much [simpler one](https://github.com/fourMs/MGT-python/blob/cf8c19bec3159c1c1b8b120cffdd6e11d58dd418/musicalgestures/_utils.py#L1206). This in theory will actually let us discard the Tkinter dependency for the future which I very well intend to do considering the pain it causes on Linux distros.
The fix is already the [latest release](https://pypi.org/project/musicalgestures/1.1.7/).
