### ISSUE TITLE
Implement directograms

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#233]
It would be cool to implement something like the directograms and related tempograms for both audio and video, as described in this paper: http://www.abedavis.com/files/papers/VisualRhythm_Davis18.pdf

**Comment by joachimpoutaraud** [comment]
Here is the `visbeat` GitHub repo designed by Abe Davis: https://github.com/abedavis/visbeat

**Comment by joachimpoutaraud** [comment]
Here is the `video-synchronization` GitHub repo designed by Brian Levis: https://github.com/brianlevis/video-synchronization

**Comment by alexarje** [comment]
Cool, did you try to make it work?

**Comment by joachimpoutaraud** [comment]
For the moment, I managed to compute directograms and design impact envelopes with peak detection. I am now starting to work on synchronizing the audio with the video frames. I can send a notebook to you and Balint tomorrow!

**Comment by joachimpoutaraud** [comment]
I have been trying to run the `main.py` file of [Brian Levis repository](https://github.com/brianlevis/video-synchronization) on my terminal in order to test the `video-synchronization` but I was first facing a `MemoryError`

![powershell](https://user-images.githubusercontent.com/63192177/149369728-6ab2c3d4-aa01-43ec-af82-8346ce077b53.jpg)

I have then tried to change the video and audio file in the `main.py` file `synchronize_video('low_audio.wav', 'low_video.mp4', 'test.mp4')` in order to see if a lower file size would work, but still, I get a `RuntimeError` because the `SoundFile` package failed to load the audio synchronized file.

![runtimeerror](https://user-images.githubusercontent.com/63192177/149373160-754ee3d9-d474-4740-831d-6ba49616eae8.jpg)
 
I'll be very interested to see if it works on your side :)

**Comment by joachimpoutaraud** [comment]
A new function to render directograms is now available [here](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_directograms.py). You can find more information on how to [implement it](https://github.com/fourMs/MGT-python/wiki/4-%E2%80%90-Video%E2%80%90based-Processes#directograms) in the wiki page.
