### ISSUE TITLE
Cropping problem in conda environment

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#251]
I am having issues with cropping inside of a Jupyter notebook running in a conda environment. The popup window shows up as expected, but it halts when pressing c to crop: `NameError: name 'w' is not defined`. Any idea what this is about?

![Screenshot 2021-12-20 at 08-57-29 Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/114316/146732293-cbf01ed5-4d0e-44e0-afdc-7f233ac54f39.png)

**Comment by dstanner** [comment]
I get this error, but no windows for cropping pops up. I get the error whenever I add the parameter `crop='manual'` when I instantiate an MgVideo object, without any cropping window opening up.

This happens with notebooks both in VSCode and standard Jupyterlab notebooks in the browser.

**Comment by joachimpoutaraud** [comment]
I just pushed an updated version of the `_cropvideo.py` file in order to fix this issue.
Now you should be able to manually crop your video by drawing a rectangle with your mouse and pressing 'c' to crop.
Note that the update is only available by downloading the repository, I'll update a new version of the MGT-python package asap.

**Comment by joachimpoutaraud** [comment]
The new release is online and you can now crop the video manually ! Here is some [documentation](https://github.com/fourMs/MGT-python/wiki/3-%E2%80%90-Preprocessing/#cropping).
