### ISSUE TITLE
show() using key does not seem to work anymore in notebook

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#253]
The cell executes instantly, but no error message is given.

**Comment by joachimpoutaraud** [comment]
I have set the parameter `embed` to `False` in the [IPython display Video](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_show.py#L97) function in order to load the video using a <video> tag and it worked on my side. I have pushed a new version on the repo, can you check if you still having this bug?

**Comment by alexarje** [comment]
This one is probably also fixed with other recent changes @joachimpoutaraud?
