### ISSUE TITLE
`.show(mode = "notebook")` and `.show()` working in with some formats, but not all and sometimes not in Spyder Notebook extension.

### ISSUE THREAD

**Issue by dana-and-monsters** [fourMs/MGT-python#256]
I use the Notebook extension in Spyder and `.show(mode = "notebook")` with a .avi doesn't work for me. I checked in Jupyter Lab and it works fine. Also, in Spyder  `.show()` works perfectly fine with .avi. This may also be an issue with the Notebook extension rather than your toolbox.

I recorded mp4s on my phone. Neither method worked for me in Spyder Notebook extension. In Jupyter Lab `.show(mode = "notebook")` works well with the mp4 but  `.show()` didn't work. However, a command like `mg.MgObject(vid, contrast = 100, brightness = -20, color = False)` is saving a new file in the directory with the videos and I can double click to watch it.

**Comment by alexarje** [comment]
I guess this one has been resolved with the latest fixes @joachimpoutaraud?

**Comment by joachimpoutaraud** [comment]
Unfortunately, it is not possible to display a video using `Spyder Notebook` at the moment as the [Spyder IPython console doesn't support html output](https://stackoverflow.com/questions/47075946/replicate-jupyter-html-output-using-ipython-and-spyder-instead). If you want to display a video inside a notebook, I recommand using `Jupyter Notebook` or `JupyterLab` when working with the toolbox as they both support such functionalities.

I have also updated the `_show.py` file in order to allow the function `.show()` to work using `JupyterLab`. I will push a new version of the toolbox asap.
