### ISSUE TITLE
Slow skip frames

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#261]
I see that the skipping function is quite slow, probably because it is recompressing the file? Might it be better to save files in .avi instead, which should probably increase the speed?

**Comment by joachimpoutaraud** [comment]
I have measured the processing time of the video when using the `skipping` function and found the following results.

| Video Files | MP4      | AVI Convertion | AVI      |   
|-------------|----------|-------------|----------|
| < 1min      | 1.6369 s | 1.8785 s    | 1.3770 s |   
| > 1min      | 6.1076 s | 7.4714 s    | 5.2524 s |   
| > 10min     | 35.370 s | 38.768 s   | 26.493 s |

When skipping frames of `avi` files, processing time gets always faster. However, when converting `mp4` to `avi` before processing the files, it adds some processing time which results in a longer total processing time. Consequently, I have hardcoded the extension to `avi` in the ffmpeg command of the `skipping` function in order to avoid the convertion of the file beforehand.
