### ISSUE TITLE
Video playback in Colab

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#277]
For workshops, it would be highly practical to have participants use Colab. Unfortunately, video playback does not work, making it difficult for people to understand what goes on. Is there a way to make videos play in notebooks or to download videos that can be played locally?

**Comment by joachimpoutaraud** [comment]
I just updated the `_show.py` file in order to be able to display videos properly in colab notebooks. It will be easier to use for future workshops. Moreover, this will makes it easier to use the latest version of the toolbox even if it hasn't been pushed on `pip`.

Here is an [colab notebook](https://colab.research.google.com/drive/1QCBC7SE2EXZ-8KcTuLsdP0D6cgYCl9Kg?usp=sharing)  example if you want to try it!
