### ISSUE TITLE
Crashing SSM on spectrogram

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#281]
I am trying to create an SSM with the spectrogram mode based on a 10-minute-long video file (the same file I have used to create SSM with motiograms). It says that it has created the spectrogram in a couple of seconds: 

![image](https://user-images.githubusercontent.com/114316/213887933-fdc3e129-1a99-49e2-b162-b98a0e10346b.png)

but then suddenly the kernel crashes without any other notice: 

![image](https://user-images.githubusercontent.com/114316/213887941-f39cd6c4-aa1b-4d71-98f0-efb1c19f12de.png)

What is wrong?

**Comment by alexarje** [comment]
I don't get the crash if I load a 2-minute-long version of the same video (generated with a skip=5). Then it generates a SSM in a few seconds: 

![image](https://user-images.githubusercontent.com/114316/213888074-93f9b14a-2ce8-447d-81a9-dd50222b955f.png)

Is it a memory issue? Strange, though, given that my laptop is quite powerful.

**Comment by joachimpoutaraud** [comment]
It might be related to a memory issue yes, because it is necessary to compute the dot product of the arrays in order to get the SSM. Consequently, it can be problematic when using long video file. However, it should not crash for a 10-minute-long video.

I need to find a way to compute the dot product in separate thread or by splitting the arrays into multiple sub-arrays.

**Comment by alexarje** [comment]
Great. I consistently get crashes when attempting to run 10-minute videos. This is on a machine with 16GB RAM.

**Comment by joachimpoutaraud** [comment]
I have updated the `_ssm.py` script with a [`slow_dot`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_ssm.py#L48) function which computes the dot product in an iterative way in order to avoid any memory error issues. This is implemented when video files are longer than ~5minutes. The drawback is that it is much slower but it has fix this issue.
