### ISSUE TITLE
Crop preview

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#288]
I have been trying to crop some 5K videos but the preview is larger than my screen, thus  I am unable to make a proper selection. So it would be good to have the preview window resizable somehow...

**Comment by joachimpoutaraud** [comment]
I have updated the [``cropping_window()``](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_cropvideo.py#L100) function in order for the user to resize the window depending on the video file dimensions. I have also updated the draw rectangle so that it will appear when the mouse moves.
