### ISSUE TITLE
Motion() chokes on rotated video files

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#289]
I just discovered that motion() doesn't like video files that have been rotated in metadata (description [here](https://www.arj.no/2021/10/27/video-rotation/)). Would be good to check for this somehow.

**Comment by joachimpoutaraud** [comment]
This was due to the fact that when rotating a video with ``ffmpeg`` by only modifying the metadata in the file, the height and the width used for the ``motion()`` function were not updated. I have updated the [``get_widthheight()``](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_utils.py#L1065) function so that it first checks if the video has been rotated by 90 degrees, and if yes it inverts the values corresponding to width and height.
