### ISSUE TITLE
Problems downloading models for pose

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#299]
When trying to use the pose method, I found that the download chokes after inserting the password: 

`ValueError: could not convert string to float: 's/'`
![Screenshot from 2023-08-03 10-17-36](https://github.com/fourMs/MGT-python/assets/114316/e7ee5384-f379-45f8-8b5b-4800b34d0144)

I think this may be because I have spaces in my password? May be worth taking that into account in the code.

**Comment by joachimpoutaraud** [comment]
Thanks for reporting this issue! I think the problem was just that your password was added to the input used for defining the `answer` variable (i.e. `'y'` or `'n'`). I have updated the Python `input()` function with `input()[0]` so that it will only take the first letter of the string variable in case the user needs to enter a password before downloading the model.

**Comment by alexarje** [comment]
I still get an error when trying this one. Do you have any ideas on what else could be wrong?

![Screenshot from 2023-10-04 14-22-57](https://github.com/fourMs/MGT-python/assets/114316/0c7a6da3-ac48-43dd-be56-8b76adafef93)

**Comment by joachimpoutaraud** [comment]
Yes I think I found the problem this time (a tricky one). It was related to the shell script (`getCOCO_remote.sh`) which caused an error because of the presence of an OD character in the url. As a result, it wasn't possible to connect to the url where the model is stored in order to be downloaded. The OD character is a carriage return, part of the CRLF sequence that Windows uses for line endings just to be different as usual.

I have updated the shell file [getCOCO_remote.sh](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/pose/getCOCO_remote.sh) and tested to download the model using Windows Subsystem for Linux (WSL) and it worked fine.
