### ISSUE TITLE
blur_faces() error 2

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#308]
The latest fix of blur_faces() removed the progress bar but introduced a new error (2)... The blurred video is saved correctly, but it chokes on saving the csv file.
![Screenshot_20231114_205321](https://github.com/fourMs/MGT-python/assets/114316/fbe7d1e6-d5d2-423a-b385-f1eae930c4c0)

**Comment by joachimpoutaraud** [comment]
When fixing the previous issue with the `blur_faces()`, I did some minor adjustements to the [`embed_audio_in_video`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_utils.py#L1338) function, but there is apparently still something I am not able to understand properly. 

There are parts of the code in the toolbox which are a bit redundant or which do not use functions already available in the toolbox. At some point, it would be great to meet with Balint to do some recap of all the functions available in the toolbox, in order to see if we need to keep them all or do some cleaning (especially in the `_utils.py` script).

For now, I have fixed the issue related to the progress bar and removed what I did on the [`embed_audio_in_video`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_utils.py#L1338) function.
