### ISSUE TITLE
Motionhistory does not work in greyscale

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#57]
When trying to run motionhistory on a greyscale video, I get the following error: 

```
Traceback (most recent call last):
  File "test_mg.py", line 18, in <module>
    mg.mg_motionhistory()
  File "../../mgmodule/_motionhistory.py", line 41, in mg_motionhistory
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Comment by fridafu** [comment]
I just ran motionhistory using the color = False flag, and it worked fine. Did you have an already black/white video and that caused an issue running with the color = True flag maybe?

**Comment by fridafu** [comment]
If that was the case, and you don't want the user to have to say colorflag = False when using a greyscale video as input (as colorflag = True is standard), it can probably be fixed with a simple test of how many color dimensions the video has. You want this?

**Comment by marcuswidmer** [comment]
When running mg_motionvideo, the video object (obtained when initialising the MgObject) is read all the way through. When mg_motionhistory is run afterwards there is no video object to read through and you get the ''!_src.empty()'' error. 

I have changed it now so that the video object, named vidcap, is obtained at the start of both mg_motionvideo and mg_motionhistory

**Comment by alexarje** [comment]
Very nice. It works fine now.
