### ISSUE TITLE
Videograms

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#73]
It would be nice to create *videograms* in addition to motiongrams. That is, to run the same matrix averaging but on the original video file instead of motion video.

**Comment by alexarje** [comment]
It may be that we should think of this as a function instead of module, similar to the way average and history works?

**Comment by alexarje** [comment]
This is an example of why videograms are interesting: http://www.arj.no/2011/07/13/videogram-of-bergensbanen/

**Comment by balintlaczko** [comment]
Okay, so there is a little bit of an issue here with the normalization, and the per-axis mean calculation. I added two implementations of videograms, one is cv2-based, the other is ffmpeg-based. In a nutshell, the dilemma is that with ffmpeg, there is no equivalent of axis-wise mean calculation (like `np.mean()` in Python or `xray.jit.mean` in Max), on the other hand it is **35-40 times faster** than the cv2-based implementation (Python) and VideoAnalysis (Max). My aim is to "tune" the ffmpeg-based implementation so that it gives us the same result as the output of VideoAnalysis, since the speed bonus is so incredibly huge (it processes a 10 second long HD 60 fps video *45 seconds faster* than "cv2", in around 1.5 seconds).


| VideoAnalysis | cv2 | ffmpeg |
| --- | --- | --- |
| <img src="https://user-images.githubusercontent.com/45127463/88323746-fcad0100-cd22-11ea-8300-2d399be22b4c.jpg" width="250"> | <img src="https://user-images.githubusercontent.com/45127463/88323847-236b3780-cd23-11ea-9ba3-24022b9c09c9.png" width="250"> | <img src="https://user-images.githubusercontent.com/45127463/88323813-18180c00-cd23-11ea-9ba8-7c11469037b0.png" width="250"> | 

It is hard to see the differences from the table, but click on the individual images in the cells to pixel-peep them. VideoAnalysis are basically the same. On the output of ffmpeg you can see a little difference on the left side, and a little bit less smoothed noise in the top gradient. The color space is also ever-so-slightly lighter.

The difference is mostly because in ffmpeg there is no axis-wise mean calculation (like `numpy.mean` in Python or `xray.jit.mean` in Max) and the way I am getting something similar is by scaling either of the axes to 1 pixel. Unfortunately this does not result in the same as calculating the mean of an axis, and I tried all the different [scaler options](https://ffmpeg.org/ffmpeg-scaler.html#scaler_005foptions) to get something similar (`area` came closest, that's the one used on the pic above), but none of them is actually calculating a mean.

But the speed difference is just insane. It feels wrong not to use a method 5x faster than real-time, opposed to another which is 1/5x real-time. 

@alexarje is this a difference we can live with? I guess the user can decide if both implementations are in the package, but which should be the default one?

**Comment by alexarje** [comment]
Yes, I think we can live very well with this. The final result is quite similar, and the speed difference is fantastic! Well done!

**Comment by balintlaczko** [comment]
Changed the default implementation of `videograms()` to the ffmpeg-based version. Example will be added to the documentation later on. In a nutshell, you can now try:
`musicalgestures.MgObject('path/to/file').videograms()`
