### ISSUE TITLE
File path string test fix in _input_test.py

### ISSUE THREAD

**Issue by shockmonger** [fourMs/MGT-python#85]
Any other file path than in the default directory raises an exception

**Comment by balintlaczko** [comment]
you mean the current dir? yeah, I am working on it, it's not just the _input_test actually... Hopefully the fix is coming soon. :)) In the meantime I found that the way the conditions were written can be simplified a bit, take a look at the current version in my repo: https://github.com/balintlaczko/MGT-python/blob/master/mgmodule/_input_test.py
